#!/bin/sh

##############################
### ---------------------#####
###ZABBIX AGENT CENTOS 7 #####
### ---------------------#####
##############################

#Script Criado para Instalação do Agent Zabbix 4.0 no CentOS 7x
#Autor: Antonio Santana
#E-mail a.fernando@hotmail.com.br

### Instala Repositório Zabbix
rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm

### Instalando Zabbix Agent

yum install zabbix-agent -y

### Inicializando Serviço do Zabbix
systemctl start zabbix-agent

### Habilitando serviço do Zabbix-Agent

systemctl enable zabbix-agent

# Modificando o de configuração do zabbix_agentd.conf

sed -i 's/Server=127.0.0.1/Server=zabbix.server/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/# ListenPort=10050/ListenPort=10050/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/# StartAgents=3/StartAgents=3/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/#ServerActive=127.0.0.1/ServerActive=zabbix.server/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/Hostname=Zabbix server/Hostname=system.hostname/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/#EnableRemoteCommands=0/EnableRemoteCommands=1/' /etc/zabbix/zabbix_agentd.conf
sed -i 's/#HostnameItem=system.hostname/HostnameItem=system.hostname/' /etc/zabbix/zabbix_agentd.conf

# Reinicializando Zabbix Agent

systemctl restart zabbix-agent 

# Checando serviço do Zabbix-Agent 

systemctl status zabbix-agent | awk '{print $1 $2 $3}' | grep 'Active:active(running)' >/tmp/zabbix-agent.log 

